### ISSUE TITLE
onion dialing through socks proxy not supported in browser setting

### ISSUE THREAD

**Issue by evbogue** [ssbc/multiserver#17] opened 2018-08-27 23:43 UTC
@staltz when I update to multiserver@1.13.3 the http://github.com/evbogue/mvd lite client breaks in the browser. I see a series of 

```
onion dialing through socks proxy not supported in browser setting
```

errors, and nothing loads. 

Since I'm not familiar with the changes, I'm just going to back up to the last version for now.

**Comment by evbogue** [comment] 2018-08-27 23:45
On second thought, I think it broke with @arj03's commits a little earlier.

**Comment by arj03** [comment] 2018-08-28 20:09
@evbogue I have tested it and it works fine for me. Both with the default install and after npm i multiserver@latest.

**Comment by arj03** [comment] 2018-08-28 20:15
Also the onion thing should just be a warning

**Comment by evbogue** [comment] 2018-08-28 20:34
@arj03 hmm, I'm not having the same experience. Out of the box `mvd` works for me, but if I remove the `package-lock.json` file, `rm -rf node_modules` and `npm install` I discover the error.

**Comment by evbogue** [comment] 2018-08-28 20:44
@arj03 But if it's just a warning, maybe it isn't multiserver that's breaking?

**Comment by arj03** [comment] 2018-09-01 20:53
@evbogue ahh, you are using decent-ws :) The problem is that your ws doesn't have a name property.

**Comment by arj03** [comment] 2018-09-03 19:36
I'm stupid. Fixed in 1.13.4. Thanks for reporting!

**Closed by arj03** 2018-09-03 19:36 UTC

**Comment by arj03** [comment] 2018-09-03 19:38
@evbogue when we merge all the new secret-stack stuff, things are going to be a lot easier, you can then specify the connections you want, so that you don't need to load e.g. onion. See this https://github.com/ssbc/ssb-config/pull/13

**Comment by evbogue** [comment] 2018-09-13 18:36
@arj03 Yah, I'm not getting this error anymore. I'm having some upgrade pains, but I'll do a little work over here to understand the new changes before I start reporting issues.
